#!/usr/bin/env node

/* eslint-disable no-console */
import path from 'node:path';
import * as esbuild from 'esbuild';
import { sassPlugin } from 'esbuild-sass-plugin';

const env = process.env.NODE_ENV ?? 'development';

const isWatch = process.argv.slice(2).includes('--watch');
const isProd = env === 'production';

const minify = isProd;
const entryPoints = [path.resolve(import.meta.dirname, 'assets', 'js', 'app.js')];
const outfile = path.resolve(import.meta.dirname, 'priv', 'static', 'assets', 'app.js');
const targets = isProd ? ['es6'] : ['esnext'];
const sourceMap = !isProd;

const config = {
  minify,
  entryPoints,
  outfile,
  target: targets,
  bundle: true,
  sourcemap: sourceMap,
  plugins: [sassPlugin({
    filter: /\.scss$/,
    quietDeps: true,
    sourceMap,
  })],
};

if (isWatch) {
  esbuild.context(config)
    .then((ctx) => ctx.watch())
    .then(() => { if (isWatch) console.log('esbuild is watching...'); })
    .catch((() => process.exit(1)));
} else {
  esbuild.build(config)
    .then(() => console.log('build finished'))
    .catch(() => process.exit(1));
}
