- name: Setup server playbook
  hosts: server
  tasks:
    - name: Fail if release_version is empty
      ansible.builtin.fail:
        msg: Error. You must pass release version!
      when: not release_version
    - name: Launch docker container
      community.docker.docker_container:
        name: cat_on_duty
        image: "{{ docker_image_name }}:{{ release_version }}"
        restart_policy: always
        state: started
        network_mode: host
        mounts:
          - source: "{{ database_dir }}"
            target: "{{ env_database_dir }}"
            propagation: shared
            read_only: false
            type: bind
        env:
          ELIXIR_ERL_OPTIONS: "{{ env_erl_options }}"
          RELEASE_DISTRIBUTION: name
          RELEASE_NAME: "{{ env_release_name }}"
          RELEASE_NODE: "{{ env_release_name }}@{{ ansible_ssh_host }}"
          RELEASE_COOKIE: "{{ env_release_cookie }}"
          PHX_HOST: "{{ ansible_ssh_host }}"
          PORT: "{{ env_port }}"
          SECRET_KEY_BASE: "{{ env_secret_key_base }}"
          DATABASE_PATH: "{{ env_database_dir }}"
          LOGIN: "{{ env_login }}"
          PASSWORD: "{{ env_password }}"
          SESSION_ENCRYPTION_SALT: "{{ env_session_encryption_salt }}"
          SESSION_SIGNING_SALT: "{{ env_session_signing_salt }}"
          LIVE_VIEW_SIGNING_SALT: "{{ env_live_view_signing_salt }}"
          TG_BOT_TOKEN: "{{ env_tg_bot_token }}"
